POST http://localhost:3003/api/games
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVsbW92aW1pbCIsImlkIjoiNmE3ZTE1MzgyNjIxM2UzYjlkMWU5ZmUyIiwiaWF0IjoxNzg2OTk4OTE1LCJleHAiOjE3ODcwMDI1MTV9.vNPnmQGTnZ5XNwwSegg_ZkmlVTSAQYgxJ7RRRxbIJbY

{
    "name" : "Hellfire Club",
    "system" : "6a7b8b42f5b8de71304a586f"
}